name: TestBackend

on:
  - push:
    - branches:
      - main

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

    - run: pytest